Samsung/Wits

README.md

This is a more complete overview of Wits setup, installation, and usage instructions.  I already can see ways it can be improved further but this should be much improved.

Major rewrite of README.md.

---

command/start.js
lib/build/buildPackage.js
lib/build/common.js
lib/build/exclusive-canonicalization.js
lib/build/launchTarget.js
lib/build/p12ToPem.js
lib/build/signPackage.js
lib/build/utils.js
lib/certificate/authorCertificateGenerator.js
lib/certificate/certificateManager.js
lib/certificate/distributorCertificateGenerator.js
lib/certificate/generateCertificate.js
lib/certificate/profilesHandler.js
lib/certificate/samsungCertificate.js
lib/certificate/tizenCertificate.js
lib/certificate/tizenCertificateViewControl.js
lib/hostAppHelper.js
lib/userInfoHelper.js
package-lock.json
package.json

start 명령에서 inquirer 질문하는 부분 삭제했습니다.

Remove asking confirm

---

command/init.js
command/start.js
index.js
lib/hostAppHelper.js
lib/userInfoHelper.js
lib/util.js
package.json

srcn에서 요구 했듯,
wits를 require 해서 다음과 같이 srcn 쪽에서 사용할 수 있도록 추가 구현하였습니다.
wits cli 환경에서도 이전과 같이 동작 가능합니다. (wits -i, wits -s, wits -w)
const wits = require('@tizentv/wits');
wits.setWitsconfigInfo(data);
wits.start();
wits.watch();
리뷰 부탁드려염

[For VSCode Extension] cli 형태 외 모듈형태로도 지원 (SRCN 요청 사항)

---

command/start.js
lib/userInfoHelper.js
package.json

Fix minor bug

---

command/init.js
command/start.js
index.js
lib/util.js
package.json

give a permission, when file is created.

give a permission

---

command/init.js
command/start.js
command/watch.js
index.js
lib/appLaunchHelper.js
lib/build/p12ToPem.js
lib/cli.js
lib/deviceConnectHelper.js
lib/hostAppHelper.js
lib/userInfoHelper.js
lib/util.js
lib/watchHelper.js
package.json

Add disconnect function

---

README.md
lib/appLaunchHelper.js
package.json

Fix bug on emulator

---

lib/cli.js

Add version information

---

lib/hostAppHelper.js
package.json

Fix contentSrc

---

lib/deviceConnectHelper.js
lib/userInfoHelper.js
lib/util.js

userdate 전역으로

---

lib/build/p12ToPem.js
lib/build/signPackage.js
lib/userInfoHelper.js
lib/util.js
package.json

Add lodash

---

command/init.js
index.js
lib/util.js
package.json

setWitsconfigInfo에 proxy 옵션 추가

setWitsconfigInfo에 proxy 옵션 추가

---

lib/userInfoHelper.js
package.json

Modify profile default path

---

package.json

version up 2.2.2

---

.gitignore
.npmignore
index.js
lib/userInfoHelper.js
package.json

Fixed isDebugMode

---

lib/userInfoHelper.js
package.json

Fix issue #61

---

README.md
doc/README_zh_HANS.md
doc/README_zh_HANT.md

Hi, Samsung team, thank your guys to develop this awesome project make easily for our TV developer. So I translate to simple/traditional Chinese to let  more developers read the document and using project more handily.

Translate document to zh_HANS/zh_HANT

---

README.md
lib/deviceConnectHelper.js
package.json

Emulator 관련 버그

---

command/init.js
lib/appLaunchHelper.js
lib/util.js
package.json

Linux Permission 관련 이슈 수정

---

lib/appLaunchHelper.js
package.json

package 파일 변경

---

command/init.js
index.js
package.json

profilePath에 대한 예외처리

---

package.json

Update webide-common-tizentv version to 1.0.11

Update webide-common-tizentv version to 1.0.11

---

.gitignore
.npmignore
command/start.js
command/watch.js
lib/cli.js
lib/userInfoHelper.js
lib/util.js
package.json

Support the value of the deviceIp as a cli option

Support the value of the deviceIp as a cli option

---

README.md

Change Atom package

---

README.md
lib/cli.js

Readme fix

---

container/js/base.js
lib/watchHelper.js

logic update when watch app code request.

Change to watchAppCode path from user cli

---

command/init.js
lib/certificationHelper.js

Remove partner level

---

command/start.js
command/watch.js
lib/appLaunchHelper.js
lib/cli.js
lib/deviceConnectHelper.js
lib/util.js
lib/watchHelper.js
package.json

Verbose feature

---

package.json

Version up socket.io(v3.1.0)

---

package.json

update tools version

---

package.json

Wits version update to 2.5.4 with @tizentv/webide-common-tizentv module version update

Version up to 2.5.4
